version: '3.8'

services:
  claude-terminal:
    build: .
    container_name: claude-terminal-orchestra
    restart: unless-stopped
    ports:
      - "8765:8080"  # Web UI and API
      - "8766:8766"  # WebSocket port for web interface
    volumes:
      - ./src/Backend/appsettings.json:/app/appsettings.json
      - ./logs:/app/logs
      - ./data:/app/data
      - claude_sessions:/root/.claude_sessions
      - claude_config:/root/.claude
      - terminal_data:/app/terminals
      - workspace:/workspace
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:8080
      # Web UI credentials (change these!)
      - WebUI__Username=admin
      - WebUI__Password=claude123
    networks:
      - claude-network

networks:
  claude-network:
    driver: bridge

volumes:
  logs:
    driver: local
  claude_sessions:
    driver: local
  claude_config:
    driver: local
  terminal_data:
    driver: local
  workspace:
    driver: local